export const authTypes = {
    LOGIN_USER: "LOGIN_USER",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

    REGISTER_USER: "REGISTER_USER",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

    LOGOUT_USER: "LOGOUT_USER",
};

export const userTypes = {
    GET_USER_DETAILS: "GET_USER_DETAILS",
    GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_FAIL: "GET_USER_DETAILS_FAIL",

    CREATE_USER: "CREATE_USER",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAIL: "CREATE_USER_FAIL",

    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

    GET_ALL_USERS: "GET_ALL_USERS",
    GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
    GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",

    DELETE_USER: "DELETE_USER",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAIL: "DELETE_USER_FAIL",

    GET_BUSINESS_DETAILS: "GET_BUSINESS_DETAILS",
    GET_BUSINESS_DETAILS_SUCCESS: "GET_BUSINESS_DETAILS_SUCCESS",
    GET_BUSINESS_DETAILS_FAIL: "GET_BUSINESS_DETAILS_FAIL",

    CREATE_BUSINESS: "CREATE_BUSINESS",
    CREATE_BUSINESS_SUCCESS: "CREATE_BUSINESS_SUCCESS",
    CREATE_BUSINESS_FAIL: "CREATE_BUSINESS_FAIL",

    DELETE_BUSINESS: "DELETE_BUSINESS",
    DELETE_BUSINESS_SUCCESS: "DELETE_BUSINESS_SUCCESS",
    DELETE_BUSINESS_FAIL: "DELETE_BUSINESS_FAIL",

    UPDATE_BUSINESS: "UPDATE_BUSINESS",
    UPDATE_BUSINESS_SUCCESS: "UPDATE_BUSINESS_SUCCESS",
    UPDATE_BUSINESS_FAIL: "UPDATE_BUSINESS_FAIL",
};

export const productTypes = {

    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAIL: "GET_ALL_PRODUCTS_FAIL",

    CREATE_PRODUCT: "CREATE_PRODUCT",
    CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",

    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

    DELETE_PRODUCT: "DELETE_PRODUCT",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",
};

export const brandTypes = {
    GET_ALL_BRANDS: "GET_ALL_BRANDS",
    GET_ALL_BRANDS_SUCCESS: "GET_ALL_BRANDS_SUCCESS",
    GET_ALL_BRANDS_FAIL: "GET_ALL_BRANDS_FAIL",

    CREATE_BRAND: "CREATE_BRAND",
    CREATE_BRAND_SUCCESS: "CREATE_BRAND_SUCCESS",
    CREATE_BRAND_FAIL: "CREATE_BRAND_FAIL",

    UPDATE_BRAND: "UPDATE_BRAND",
    UPDATE_BRAND_SUCCESS: "UPDATE_BRAND_SUCCESS",
    UPDATE_BRAND_FAIL: "UPDATE_BRAND_FAIL",

    DELETE_BRAND: "DELETE_BRAND",
    DELETE_BRAND_SUCCESS: "DELETE_BRAND_SUCCESS",
    DELETE_BRAND_FAIL: "DELETE_BRAND_FAIL",

};


export const cartTypes = {
    GET_CART: "GET_CART",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",

    CHECKOUT: "CHECKOUT",
    CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
    CHECKOUT_FAIL: "CHECKOUT_FAIL",
};